CREATE TABLE IF NOT EXISTS account (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_name VARCHAR(255),
  balance DECIMAL(19, 2),
  created_date TIMESTAMP,
  last_modified_date TIMESTAMP,
  created_by VARCHAR(255),
  last_modified_by VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS transaction (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  debtor_account_id BIGINT NOT NULL,
  creditor_account_id BIGINT NOT NULL,
  amount DECIMAL(19, 2) NOT NULL,
  status SMALLINT NOT NULL,
  created_date TIMESTAMP,
  last_modified_date TIMESTAMP,
  created_by VARCHAR(255),
  last_modified_by VARCHAR(255),
  CONSTRAINT fk_transaction_debtor_account FOREIGN KEY (debtor_account_id) REFERENCES account (id),
  CONSTRAINT fk_transaction_creditor_account FOREIGN KEY (creditor_account_id) REFERENCES account (id)
);
